# Generated by Django 3.0.5 on 2020-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('fazar', models.CharField(default=None, max_length=10)),
                ('zohar', models.CharField(default=None, max_length=10)),
                ('asar', models.CharField(default=None, max_length=10)),
                ('magrib', models.CharField(default=None, max_length=10)),
                ('isha', models.CharField(default=None, max_length=10)),
                ('juma_khutba', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
