# Generated by Django 3.0.3 on 2020-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjid',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='asar',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='fazar',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='isha',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='juma_khutba',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='magrib',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='masjid',
            name='zohar',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
